# ROS2 Controllers configuration for Doosan M0609
# This file defines the controller configuration for the robot's 6 joints

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz - Control loop frequency
    
    # List of controllers to be loaded by controller manager
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint1
      - joint2  
      - joint3
      - joint4
      - joint5
      - joint6
    interfaces:
      - position
      - velocity
    # Publish rate for joint states (Hz)
    publish_rate: 50.0

# Joint Trajectory Controller Configuration  
joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3 
      - joint4
      - joint5
      - joint6
      
    # Command interfaces that the controller will use
    command_interfaces:
      - position
      # - velocity  # Uncomment if velocity control needed
      
    # State interfaces that the controller will read
    state_interfaces:
      - position
      - velocity
      
    # Allow integration in goal trajectories for better tracking
    allow_integration_in_goal_trajectories: true
    
    # Action server configuration
    action_monitor_rate: 20.0  # Hz
    
    # Tolerances for trajectory execution
    constraints:
      stopped_velocity_tolerance: 0.01  # rad/s
      goal_time: 0.6  # seconds - Time tolerance for reaching goal
      
      # Per-joint position tolerances (radians)
      joint1: 
        trajectory: 0.05
        goal: 0.02
      joint2:
        trajectory: 0.05 
        goal: 0.02
      joint3:
        trajectory: 0.05
        goal: 0.02
      joint4:
        trajectory: 0.05
        goal: 0.02
      joint5:
        trajectory: 0.05
        goal: 0.02
      joint6:
        trajectory: 0.05
        goal: 0.02
        
    # Command publication settings
    gains:
      joint1:
        p: 100.0
        d: 1.0
        i: 0.01
        i_clamp: 1.0
      joint2:
        p: 100.0
        d: 1.0
        i: 0.01
        i_clamp: 1.0
      joint3:
        p: 100.0
        d: 1.0
        i: 0.01
        i_clamp: 1.0
      joint4:
        p: 100.0
        d: 1.0
        i: 0.01
        i_clamp: 1.0
      joint5:
        p: 100.0
        d: 1.0
        i: 0.01
        i_clamp: 1.0
      joint6:
        p: 100.0
        d: 1.0
        i: 0.01
        i_clamp: 1.0