slam_toolbox:
  ros__parameters:
    use_sim_time: false
    resolution: 0.05
    publish_period_sec: 0.05
    max_laser_range: 15.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.05
    map_update_interval: 3.0
    scan_topic: /robot4/scan
    map_file_name: "map"
    mode: "mapping"
    use_scan_matching: true
    enable_loop_closure: true
    loop_match_min_chain_size: 10
    loop_match_max_distance: 3.0
