controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Hardware interface configuration
    hardware_interfaces:
      - name: doosan_m0609
        type: doosan_m0609_hardware/DsrHw2
        parameters:
          robot_ip: "192.168.137.100"
          robot_port: 12345
          
    # Joint state broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Position controller for joint control
    position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    interface_name: position